# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54013d2fd2173fa62f39360de360d983fd40887d6ede27831193dfaf042a40129aa15ecc549ae5629c570a39c4d322f2877de93f25320593e9245c4a4658752c

test:
  secret_key_base: 3c585446902a09c0ff6671edb2d0b353e8bcaa5f6a5e31a83c5a34cc8771946d434771771158a8a8936db8685459f4bfd26c72c0f437eb040a52aba11fae3b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
